### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by paulomorgado** [security-code-scan/security-code-scan-results-action#2]
I'm getting this error:

```text
2021-07-08T07:40:28.5323142Z ##[group]Run security-code-scan/security-code-scan-results-action@main
2021-07-08T07:40:28.5323987Z with:
2021-07-08T07:40:28.5324433Z   sarif_directory: ../results
2021-07-08T07:40:28.5324804Z env:
2021-07-08T07:40:28.5325356Z   NUGET: C:\hostedtoolcache\windows\nuget.exe\5.10.0\x64/nuget.exe
2021-07-08T07:40:28.5326087Z ##[endgroup]
2021-07-08T07:40:33.7776972Z You can invoke the tool using the following command: sarif
2021-07-08T07:40:33.7778165Z Tool 'sarif.multitool' (version '2.3.10') was successfully installed.
2021-07-08T07:40:43.2192577Z D:\a\Microsoft.Extensions.AspNet\Microsoft.Extensions.AspNet\convert.js:12
2021-07-08T07:40:43.2194554Z     run.tool.driver.rules = run.tool.driver.rules.filter((e => e.id.startsWith("SCS")));
2021-07-08T07:40:43.2195578Z                                                   ^
2021-07-08T07:40:43.2195957Z 
2021-07-08T07:40:43.2196729Z TypeError: Cannot read property 'filter' of undefined
2021-07-08T07:40:43.2199700Z     at Object.<anonymous> (D:\a\Microsoft.Extensions.AspNet\Microsoft.Extensions.AspNet\convert.js:12:51)
2021-07-08T07:40:43.2201166Z     at Module._compile (internal/modules/cjs/loader.js:1085:14)
2021-07-08T07:40:43.2202090Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2021-07-08T07:40:43.2202947Z     at Module.load (internal/modules/cjs/loader.js:950:32)
2021-07-08T07:40:43.2203976Z     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
2021-07-08T07:40:43.2205158Z     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
2021-07-08T07:40:43.2206709Z     at internal/main/run_main_module.js:17:47
2021-07-08T07:40:43.2312568Z ##[error]Process completed with exit code 1.
```

**Comment by paulomorgado** [comment]
Solved with https://github.com/paulomorgado/Microsoft.Extensions.AspNet/blob/b759ef0dc402fff2ead50f082f7fecb66c619f86/.github/workflows/securitycodescan-analysis.yml#L150-L249

I can submit a PR.

**Comment by JarLob** [comment]
Hi, sorry didn't see all the issues. GitHub didn't add me to the watch list automatically.
PR would be awesome. What was the cause?

**Comment by paulomorgado** [comment]
I'm not sure why this task was a bash script creating a js script and using node to run it.

I just converted to pwsh and have no errors now.

But I don't know if it does everything it was supposed to do.

**Comment by JarLob** [comment]
Fixed in https://github.com/security-code-scan/security-code-scan-add-action/releases/tag/v1.2

**Comment by JarLob** [comment]
Odd, so looks like `run.tool.driver.rules` is undefined. Do you have a link to the failed workflow run?
